# Use a specific version of the base Python image
ARG PYTHON_VERSION=3.14.6-slim-bookworm

FROM python:${PYTHON_VERSION} AS python


# Set ARGs and ENVs
ARG APP_HOME=/app

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
WORKDIR ${APP_HOME}
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
ARG JDK_VERSION=21


# Update package lists and install required packages
RUN apt-get -qq update && \
    apt-get -qq -y --no-install-recommends install gnupg ca-certificates locales curl tzdata git && \
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && \
    locale-gen en_US.UTF-8 && \
    curl -fsSL https://repos.azul.com/azul-repo.key \
        | gpg --dearmor -o /usr/share/keyrings/azul.gpg && \
    chmod 644 /usr/share/keyrings/azul.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/azul.gpg] https://repos.azul.com/zulu/deb stable main" \
        > /etc/apt/sources.list.d/zulu.list && \
    apt-get -qq update && \
    apt-get -qq -y upgrade && \
    apt-get -qq -y --no-install-recommends install zulu${JDK_VERSION}-jdk && \
    apt-get -qq -y purge gnupg curl && \
    apt-get -y autoremove && \
    rm -rf /var/lib/apt/lists/*

# Set Java home environment variable
RUN JAVA_BIN="$(readlink -f "$(command -v java)")" && \
    JAVA_HOME="${JAVA_BIN%/bin/java}" && \
    ln -s "$JAVA_HOME" /opt/java-home

ENV JAVA_HOME=/opt/java-home
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# Ensure curl and jq are available for the next step
RUN apt-get update && \
    apt-get install -y curl jq libssl3 && \
    rm -rf /var/lib/apt/lists/*
ENV PATH="/usr/local/bin:${PATH}"
# Now use them safely
RUN set -eux; \
    ARCH="$(uname -m)"; \
    case "$ARCH" in \
        x86_64) ARCH_NAME="x86_64-unknown-linux-gnu" ;; \
        aarch64) ARCH_NAME="aarch64-unknown-linux-gnu" ;; \
        *) echo "Unsupported arch: $ARCH" && exit 1 ;; \
    esac; \
    URL=$(curl -s https://api.github.com/repos/EFForg/apkeep/releases/latest \
        | jq -r ".assets[] | select(.name == \"apkeep-${ARCH_NAME}\") | .browser_download_url"); \
    curl -L "$URL" -o /usr/local/bin/apkeep; \
    chmod +x /usr/local/bin/apkeep; \
    echo "Installed apkeep from $URL"; \
    /usr/local/bin/apkeep --version

CMD ["bash"]
