APK_MIRROR_BASE_URL = "https://www.apkmirror.com"
APK_MIRROR_BASE_APK_URL = f"{APK_MIRROR_BASE_URL}/apk"
UPTODOWN_BASE_URL = "https://{}.en.uptodown.com/android"
APK_PURE_URL = "https://d.apkpure.com/b/APK/{}?version=latest"
APK_SOS_URL = "https://apksos.com/download-app/{}"
GITHUB_BASE_URL = "https://github.com"
apk_sources = {
    "reddit": f"{APK_MIRROR_BASE_APK_URL}/redditinc/reddit/",
    "twitter": f"{APK_MIRROR_BASE_APK_URL}/x-corp/twitter/",
    "tiktok": f"{APK_MIRROR_BASE_APK_URL}/tiktok-pte-ltd/tik-tok-including-musical-ly/",
    "warnwetter": f"{APK_MIRROR_BASE_APK_URL}/deutscher-wetterdienst/warnwetter/",
    "youtube": f"{APK_MIRROR_BASE_APK_URL}/google-inc/youtube/",
    "youtube_music": f"{APK_MIRROR_BASE_APK_URL}/google-inc/youtube-music/",
    "ticktick": f"{APK_MIRROR_BASE_APK_URL}/appest-inc/ticktick-to-do-list-with-reminder-day-planner/",
    "icon_pack_studio": f"{APK_MIRROR_BASE_APK_URL}/smart-launcher-team/icon-pack-studio/",
    "windy": f"{APK_MIRROR_BASE_APK_URL}/windy-weather-world-inc/windy-wind-weather-forecast/",
    "tasker": f"{APK_MIRROR_BASE_APK_URL}/joaomgcd/tasker-crafty-apps-eu/",
    "vsco": f"{APK_MIRROR_BASE_APK_URL}/vsco/vsco-cam/",
    "nova_launcher": f"{APK_MIRROR_BASE_APK_URL}/teslacoil-software/nova-launcher/",
    "netguard": f"{APK_MIRROR_BASE_APK_URL}/marcel-bokhorst/netguard-no-root-firewall/",
    "instagram": f"{APK_MIRROR_BASE_APK_URL}/instagram/instagram-instagram/",
    "inshorts": f"{APK_MIRROR_BASE_APK_URL}/inshorts-formerly-news-in-shorts/",
    "messenger": f"{APK_MIRROR_BASE_APK_URL}/facebook-2/messenger/",
    "trakt": f"{APK_MIRROR_BASE_APK_URL}/trakt/trakt/",
    "candyvpn": f"{APK_MIRROR_BASE_APK_URL}/liondev-io/candylink-vpn/",
    "sonyheadphone": f"{APK_MIRROR_BASE_APK_URL}/sony-corporation/sony-headphones-connect/",
    "boost": f"{APK_MIRROR_BASE_APK_URL}/ruben-mayayo/boost-for-reddit/",
    "rif": f"{APK_MIRROR_BASE_APK_URL}/talklittle/reddit-is-fun/",
    "sync": f"{APK_MIRROR_BASE_APK_URL}/red-apps-ltd/sync-for-reddit/",
    "infinity": f"{APK_MIRROR_BASE_APK_URL}/docile-alligator/infinity-for-reddit/",
    "slide": f"{APK_MIRROR_BASE_APK_URL}/haptic-apps/slide-for-reddit/",
    "bacon": f"{APK_MIRROR_BASE_APK_URL}/onelouder-apps/baconreader-for-reddit/",
    "pixiv": f"{APK_MIRROR_BASE_APK_URL}/pixiv-inc/pixiv/",
    "spotify": UPTODOWN_BASE_URL.format("spotify"),
    "nyx-music-player": UPTODOWN_BASE_URL.format("nyx-music-player"),
    "my-expenses": UPTODOWN_BASE_URL.format("my-expenses"),
    "backdrops": UPTODOWN_BASE_URL.format("backdrops"),
    "twitch": UPTODOWN_BASE_URL.format("twitch"),
    "irplus": UPTODOWN_BASE_URL.format("irplus"),
    "meme-generator-free": UPTODOWN_BASE_URL.format("meme-generator-free"),
    "yuka": UPTODOWN_BASE_URL.format("yuka"),
    "relay": UPTODOWN_BASE_URL.format("relay"),
    "grecorder": UPTODOWN_BASE_URL.format("opnemer"),
    "hex-editor": APK_PURE_URL,
    "androidtwelvewidgets": APK_PURE_URL,
    "expensemanager": APK_SOS_URL,
}
